# -*- coding: utf-8 -*-
"""audio-compression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z9rUoiFby59toO9hIL-EDVXAf8aeMdum

Ini adalah tugas sistem multimedia

Kompresi audio menggunakan metode lossy dan losless.

Elmi Wahyu Triyani - 1217050045

# Menginstall Library
"""

!pip install pydub soundfile
!apt-get install ffmpeg

"""# Mengunggah File Audio"""

from google.colab import files

uploaded = files.upload()

for filename in uploaded.keys():
    print(f'User uploaded file "{filename}" with length {len(uploaded[filename])} bytes')

"""# Mengkompresi Audio - Lossy
File yan telah dikompresi dapat dilihat pada menu files dengan klik ikon folder sebelah kiri layar Google Colab dengan nama file compressed_audio_lossy
"""

from pydub import AudioSegment

input_file = list(uploaded.keys())[0]
output_file_lossy = 'compressed_audio_lossy.mp3'

audio = AudioSegment.from_file(input_file)

audio.export(output_file_lossy, format='mp3', bitrate='128k')

print(f"File audio berhasil dikompresi ke {output_file_lossy}")

"""Download File yang telah dikompresi - lossy

"""

from google.colab import files

files.download(output_file_lossy)

"""# Mengkompresi Audio - Lossles

"""

temp_wav_file = 'temp_audio.wav'
audio.export(temp_wav_file, format='wav')

import soundfile as sf

output_file_lossless = 'compressed_audio_lossles.flac'

data, samplerate = sf.read(temp_wav_file)

sf.write(output_file_lossless, data, samplerate, format='FLAC')

print(f"File audio berhasil dikompresi ke {output_file_lossless}")

"""Download File yang telah dikompresi - Lossles"""

from google.colab import files
files.download(output_file_lossless)