# -*- coding: utf-8 -*-
"""video-compression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HE9kdfbuMtHKxeN6aUYVGHRkbSc1Kwc

Ini adalah tugas sistem multimedia

Kompresi video menggunakan metode lossy dan losless.

Elmi Wahyu Triyani - 1217050045

# Menginstall Library
"""

# ffmpeg
!apt-get install -y ffmpeg
#  moviepy
!pip install moviepy

"""# Mengunggah Video ke Google Colab"""

from google.colab import files
import os

# Unggah video asli
uploaded = files.upload()

# Ambil nama file video yang diunggah
input_video = next(iter(uploaded.keys()))

# Tampilkan ukuran file sebelum kompresi
file_size_before = os.path.getsize(input_video) / (1024 * 1024)  # Ukuran dalam MB
print(f"Ukuran file sebelum kompresi: {file_size_before:.2f} MB")

"""#Kompresi Video - Lossy"""

import subprocess

# Nama output file untuk kompresi Lossy
output_lossy_path = 'compressed_video_lossy.mp4'

# Kompresi Lossy menggunakan ffmpeg dengan bitrate lebih rendah
subprocess.call(['ffmpeg', '-i', input_video, '-b:v', '1000k', output_lossy_path])

# Tampilkan ukuran file setelah kompresi Lossy
file_size_lossy = os.path.getsize(output_lossy_path) / (1024 * 1024)  # Ukuran dalam MB
print(f"Ukuran file setelah kompresi Lossy: {file_size_lossy:.2f} MB")

# Unduh video yang telah dikompresi (Lossy)
files.download(output_lossy_path)

# Tampilkan pesan setelah file berhasil diunduh
print("File telah selesai diunduh.")

"""# Kompresi Video-Lossles

"""

# Nama output file untuk kompresi Lossless
output_lossless_path = 'compressed_video_lossless.mp4'

# Kompresi Lossless menggunakan ffmpeg
subprocess.call(['ffmpeg', '-i', input_video, '-c:v', 'libx264', '-preset', 'veryslow', '-crf', '0', output_lossless_path])

file_size_lossless = os.path.getsize(output_lossless_path) / (1024 * 1024)  # Ukuran dalam MB
print(f"Ukuran file setelah kompresi Lossless: {file_size_lossless:.2f} MB")

# Unduh video yang telah dikompresi (Lossless)
files.download(output_lossless_path)

# Tampilkan pesan setelah file berhasil diunduh
print("File telah selesai diunduh.")